### PR TITLE
Assigned newly connectivity-enforced clusters to the clusters instance variable.

### PR DESCRIPTION
**Pull request by CalumMurray**

### CODE REVIEW

**Comment by CalumMurray** [comment]
When create_connectivity() was called, it only updated the local clusters copy.

**Comment by CalumMurray** [comment]
Actually, having done this, it seems to corrupt the cluster indexing, locations etc.
Any ideas?

**Comment by PSMM** [comment]
There is indeed something not right in that function. I've got that part 
not from the paper, but from the corresponding source code:
http://ivrg.epfl.ch/research/superpixels

Maybe something is done wrong here what has been done right in their 
code. It's been a while since I've seen that code, but it might also not 
be a vital part of the process.

**Comment by CalumMurray** [comment]
I've had a look through the original source code, and I can't see anything wrong really.  But I guess, as well as reassigning clusters = new_clusters, you'll also need to reassign the centers, distances and center_counts?
I've also updated this to work with the newer OpenCV 2 API by the way (e.g. cv::Mat and friends).

**Comment by CalumMurray** [comment]
What I've done is append "create_connectivity()" to the end of "generate_superpixels()", then re run the code commented
/\* Clear the center values. _/
/_ Compute the new cluster centers. _/
/_ Normalize the clusters. */

Which looks like it's working so far, although there will almost certainly be a more efficient way to do it inline while create_connectivity is running or something.

**Pull request closed without merging**
